In [6]:
import pandas as pd

# Analisando os dados que se encotram no data/raw (dataset_kobe_dev.parquet e dataset_kobe_prod.parque)

In [7]:

# Caminho do arquivo Parquet
df_dataset_kobe_dev = pd.read_parquet("../data/01_raw/dataset_kobe_dev.parquet", engine="pyarrow")  # ou engine="fastparquet"
df_dataset_kobe_prod = pd.read_parquet("../data/01_raw/dataset_kobe_prod.parquet", engine="pyarrow")  # ou engine="fastparquet"

print(df_dataset_kobe_dev.head())
print("________________________________________________________________________________________________")
print(df_dataset_kobe_dev.describe())
print("________________________________________________________________________________________________")
print(df_dataset_kobe_dev.info())
print("________________________________________________________________________________________________")

print()
print("-------------------------------------------------------------------------------------------------")
print()

print(df_dataset_kobe_prod.head())
print("________________________________________________________________________________________________")
print(df_dataset_kobe_prod.describe())
print("________________________________________________________________________________________________")
print(df_dataset_kobe_prod.info())

         action_type combined_shot_type  game_event_id   game_id      lat  \
0          Jump Shot          Jump Shot             10  20000012  33.9723
1          Jump Shot          Jump Shot             12  20000012  34.0443
2          Jump Shot          Jump Shot             35  20000012  33.9093
3          Jump Shot          Jump Shot             43  20000012  33.8693
4  Driving Dunk Shot               Dunk            155  20000012  34.0443

   loc_x  loc_y       lon  minutes_remaining  period  ...       shot_type  \
0    167     72 -118.1028                 10       1  ...  2PT Field Goal
1   -157      0 -118.4268                 10       1  ...  2PT Field Goal
2   -101    135 -118.3708                  7       1  ...  2PT Field Goal
3    138    175 -118.1318                  6       1  ...  2PT Field Goal
4      0      0 -118.2698                  6       2  ...  2PT Field Goal

          shot_zone_area  shot_zone_basic  shot_zone_range     team_id  \
0          Right Side(R)        Mid-Range        16-24 ft.  1610612747
1           Left Side(L)        Mid-Range         8-16 ft.  1610612747
2   Left Side Center(LC)        Mid-Range        16-24 ft.  1610612747
3  Right Side Center(RC)        Mid-Range        16-24 ft.  1610612747
4              Center(C)  Restricted Area  Less Than 8 ft.  1610612747

            team_name   game_date    matchup opponent  shot_id
0  Los Angeles Lakers  2000-10-31  LAL @ POR      POR        1
1  Los Angeles Lakers  2000-10-31  LAL @ POR      POR        2
2  Los Angeles Lakers  2000-10-31  LAL @ POR      POR        3
3  Los Angeles Lakers  2000-10-31  LAL @ POR      POR        4
4  Los Angeles Lakers  2000-10-31  LAL @ POR      POR        5

[5 rows x 25 columns]
________________________________________________________________________________________________
       game_event_id       game_id           lat         loc_x         loc_y  \
count   24271.000000  2.427100e+04  24271.000000  24271.000000  24271.000000
mean      240.571464  2.483294e+07     33.980603      7.407935     63.697417
std       148.513569  7.816366e+06      0.065872     93.601652     65.871523
min         2.000000  2.000001e+07     33.543300   -218.000000    -44.000000
25%       102.000000  2.040094e+07     33.925300    -44.000000      0.000000
50%       244.000000  2.090015e+07     33.999300      0.000000     45.000000
75%       355.000000  2.960106e+07     34.044300     75.000000    119.000000
max       659.000000  4.990009e+07     34.088300    220.000000    501.000000

                lon  minutes_remaining        period      playoffs  \
count  24271.000000       24271.000000  24271.000000  24271.000000
mean    -118.262392           5.091591      2.470520      0.149026
std        0.093602           3.420637      1.149706      0.356121
min     -118.487800           0.000000      1.000000      0.000000
25%     -118.313800           2.000000      1.000000      0.000000
50%     -118.269800           5.000000      3.000000      0.000000
75%     -118.194800           8.000000      3.000000      0.000000
max     -118.049800          11.000000      7.000000      1.000000

       seconds_remaining  shot_distance  shot_made_flag       team_id  \
count       24271.000000   24271.000000    20285.000000  2.427100e+04
mean           28.758271      10.222076        0.477348  1.610613e+09
std            17.390267       7.574579        0.499499  0.000000e+00
min             0.000000       0.000000        0.000000  1.610613e+09
25%            14.000000       1.000000        0.000000  1.610613e+09
50%            29.000000      12.000000        0.000000  1.610613e+09
75%            44.000000      17.000000        1.000000  1.610613e+09
max            59.000000      50.000000        1.000000  1.610613e+09

            shot_id
count  24271.000000
mean   15160.124593
std     9010.341515
min        1.000000
25%     7206.500000
50%    15081.000000
75%    23268.500000
max    30697.000000
________________________________________________________________________________________________
<class 'pandas.core.frame.DataFrame'>
Index: 24271 entries, 0 to 30696
Data columns (total 25 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   action_type         24271 non-null  object
 1   combined_shot_type  24271 non-null  object
 2   game_event_id       24271 non-null  int64
 3   game_id             24271 non-null  int64
 4   lat                 24271 non-null  float64
 5   loc_x               24271 non-null  int64
 6   loc_y               24271 non-null  int64
 7   lon                 24271 non-null  float64
 8   minutes_remaining   24271 non-null  int64
 9   period              24271 non-null  int64
 10  playoffs            24271 non-null  int64
 11  season              24271 non-null  object
 12  seconds_remaining   24271 non-null  int64
 13  shot_distance       24271 non-null  int64
 14  shot_made_flag      20285 non-null  float64
 15  shot_type           24271 non-null  object
 16  shot_zone_area      24271 non-null  object
 17  shot_zone_basic     24271 non-null  object
 18  shot_zone_range     24271 non-null  object
 19  team_id             24271 non-null  int64
 20  team_name           24271 non-null  object
 21  game_date           24271 non-null  object
 22  matchup             24271 non-null  object
 23  opponent            24271 non-null  object
 24  shot_id             24271 non-null  int64
dtypes: float64(3), int64(11), object(11)
memory usage: 4.8+ MB
None
________________________________________________________________________________________________

-------------------------------------------------------------------------------------------------

   action_type combined_shot_type  game_event_id   game_id      lat  loc_x  \
10   Jump Shot          Jump Shot            309  20000012  33.8063    -94
17   Jump Shot          Jump Shot            138  20000019  33.8183   -117
27   Jump Shot          Jump Shot            369  20000019  33.8583   -183
39   Jump Shot          Jump Shot            202  20000047  33.7723    -27
54   Jump Shot          Jump Shot             60  20000049  33.7973   -141

    loc_y       lon  minutes_remaining  period  ...       shot_type  \
10    238 -118.3638                  1       3  ...  3PT Field Goal
17    226 -118.3868                  8       2  ...  3PT Field Goal
27    186 -118.4528                  0       3  ...  3PT Field Goal
39    272 -118.2968                  0       2  ...  3PT Field Goal
54    247 -118.4108                  4       1  ...  3PT Field Goal

          shot_zone_area    shot_zone_basic  shot_zone_range     team_id  \
10  Left Side Center(LC)  Above the Break 3          24+ ft.  1610612747
17  Left Side Center(LC)  Above the Break 3          24+ ft.  1610612747
27  Left Side Center(LC)  Above the Break 3          24+ ft.  1610612747
39             Center(C)  Above the Break 3          24+ ft.  1610612747
54  Left Side Center(LC)  Above the Break 3          24+ ft.  1610612747

             team_name   game_date      matchup opponent  shot_id
10  Los Angeles Lakers  2000-10-31    LAL @ POR      POR       11
17  Los Angeles Lakers  2000-11-01  LAL vs. UTA      UTA       18
27  Los Angeles Lakers  2000-11-01  LAL vs. UTA      UTA       28
39  Los Angeles Lakers  2000-11-04    LAL @ VAN      VAN       40
54  Los Angeles Lakers  2000-11-05  LAL vs. LAC      LAC       55

[5 rows x 25 columns]
________________________________________________________________________________________________
       game_event_id       game_id          lat        loc_x        loc_y  \
count    6426.000000  6.426000e+03  6426.000000  6426.000000  6426.000000
mean      281.746032  2.450391e+07    33.849664     5.987084   194.635543
std       151.143268  7.514467e+06     0.082910   157.617034    82.909851
min         2.000000  2.000001e+07    33.253300  -250.000000   -35.000000
25%       164.000000  2.050084e+07    33.805300  -152.000000   167.000000
50%       291.000000  2.090113e+07    33.835300    12.000000   209.000000
75%       408.000000  2.150085e+07    33.877300   154.000000   239.000000
max       634.000000  4.990009e+07    34.079300   248.000000   791.000000

               lon  minutes_remaining       period     playoffs  \
count  6426.000000        6426.000000  6426.000000  6426.000000
mean   -118.263813           4.107688     2.704171     0.137255
std       0.157617           3.449276     1.149971     0.344143
min    -118.519800           0.000000     1.000000     0.000000
25%    -118.421800           1.000000     2.000000     0.000000
50%    -118.257800           4.000000     3.000000     0.000000
75%    -118.115800           7.000000     4.000000     0.000000
max    -118.021800          11.000000     7.000000     1.000000

       seconds_remaining  shot_distance  shot_made_flag       team_id  \
count        6426.000000    6426.000000     5412.000000  6.426000e+03
mean           26.880019      25.581855        0.329268  1.610613e+09
std            17.732805       4.067015        0.469991  0.000000e+00
min             0.000000       0.000000        0.000000  1.610613e+09
25%            11.000000      24.000000        0.000000  1.610613e+09
50%            27.000000      25.000000        0.000000  1.610613e+09
75%            42.000000      26.000000        1.000000  1.610613e+09
max            59.000000      79.000000        1.000000  1.610613e+09

            shot_id
count   6426.000000
mean   16062.382353
std     8237.432519
min       11.000000
25%     8983.750000
50%    16373.000000
75%    22598.750000
max    30696.000000
________________________________________________________________________________________________
<class 'pandas.core.frame.DataFrame'>
Index: 6426 entries, 10 to 30695
Data columns (total 25 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   action_type         6426 non-null   object
 1   combined_shot_type  6426 non-null   object
 2   game_event_id       6426 non-null   int64
 3   game_id             6426 non-null   int64
 4   lat                 6426 non-null   float64
 5   loc_x               6426 non-null   int64
 6   loc_y               6426 non-null   int64
 7   lon                 6426 non-null   float64
 8   minutes_remaining   6426 non-null   int64
 9   period              6426 non-null   int64
 10  playoffs            6426 non-null   int64
 11  season              6426 non-null   object
 12  seconds_remaining   6426 non-null   int64
 13  shot_distance       6426 non-null   int64
 14  shot_made_flag      5412 non-null   float64
 15  shot_type           6426 non-null   object
 16  shot_zone_area      6426 non-null   object
 17  shot_zone_basic     6426 non-null   object
 18  shot_zone_range     6426 non-null   object
 19  team_id             6426 non-null   int64
 20  team_name           6426 non-null   object
 21  game_date           6426 non-null   object
 22  matchup             6426 non-null   object
 23  opponent            6426 non-null   object
 24  shot_id             6426 non-null   int64
dtypes: float64(3), int64(11), object(11)
memory usage: 1.3+ MB
None

# Tratamento dos dados brutos

In [8]:
# Mantendo somente as colunas [lat, lng, minutes remaining, period, playoffs, shot_distance, shot_made_flag]
df_dataset_kobe_dev = df_dataset_kobe_dev[["lat", "lon", "minutes_remaining", "period", "playoffs", "shot_distance", "shot_made_flag"]]
df_dataset_kobe_prod = df_dataset_kobe_prod[["lat", "lon", "minutes_remaining", "period", "playoffs", "shot_distance", "shot_made_flag"]]

# Verificando se existem valores nulos
rows_with_nulls_kobe_dev = df_dataset_kobe_dev[df_dataset_kobe_dev.isnull().any(axis=1)]
print(rows_with_nulls_kobe_dev)

print("----------------------------------------------------------------------------------------------")

rows_with_nulls_kobe_prod = df_dataset_kobe_prod[df_dataset_kobe_prod.isnull().any(axis=1)]
print(rows_with_nulls_kobe_prod)

print(df_dataset_kobe_dev["shot_made_flag"].value_counts())
print("________________________________________________________________________________________________")
print(df_dataset_kobe_prod["shot_made_flag"].value_counts())
print("________________________________________________________________________________________________")

df_dataset_kobe_dev.dropna(inplace=True)
df_dataset_kobe_prod.dropna(inplace=True)

df_dataset_kobe_dev["shot_made_flag"] = df_dataset_kobe_dev["shot_made_flag"].astype(int)
df_dataset_kobe_prod["shot_made_flag"] = df_dataset_kobe_prod["shot_made_flag"].astype(int)

print(df_dataset_kobe_dev.info())

print()
print("-------------------------------------------------------------------------------------------------")
print()

print(df_dataset_kobe_prod.info())

           lat       lon  minutes_remaining  period  playoffs  shot_distance  \
0      33.9723 -118.1028                 10       1         0             18
7      34.0163 -118.2688                  8       3         0              2
16     34.0443 -118.2698                  0       1         0              0
19     34.0443 -118.2698                 10       3         0              0
32     33.9683 -118.1068                 11       1         0             17
...        ...       ...                ...     ...       ...            ...
30668  33.8223 -118.2928                  7       4         1             22
30680  34.0443 -118.2698                  0       2         1              0
30682  33.9963 -118.3378                 11       3         1              8
30686  33.9513 -118.2538                  5       3         1              9
30693  34.0443 -118.2698                  6       4         1              0

       shot_made_flag
0                 NaN
7                 NaN
16                NaN
19                NaN
32                NaN
...               ...
30668             NaN
30680             NaN
30682             NaN
30686             NaN
30693             NaN

[3986 rows x 7 columns]
----------------------------------------------------------------------------------------------
           lat       lon  minutes_remaining  period  playoffs  shot_distance  \
54     33.7973 -118.4108                  4       1         0             28
59     33.8033 -118.1238                  3       2         0             28
143    34.0333 -118.0328                  4       1         0             23
209    33.8883 -118.4838                  5       4         0             26
316    33.8273 -118.3868                  9       4         0             24
...        ...       ...                ...     ...       ...            ...
30395  33.8303 -118.1378                  1       4         1             25
30415  33.9233 -118.4838                  1       3         1             24
30431  33.7833 -118.3058                  4       4         1             26
30510  33.8113 -118.3888                  3       1         1             26
30583  33.9663 -118.4968                  2       4         1             24

       shot_made_flag
54                NaN
59                NaN
143               NaN
209               NaN
316               NaN
...               ...
30395             NaN
30415             NaN
30431             NaN
30510             NaN
30583             NaN

[1014 rows x 7 columns]
shot_made_flag
0.0    10602
1.0     9683
Name: count, dtype: int64
________________________________________________________________________________________________
shot_made_flag
0.0    3630
1.0    1782
Name: count, dtype: int64
________________________________________________________________________________________________
<class 'pandas.core.frame.DataFrame'>
Index: 20285 entries, 1 to 30696
Data columns (total 7 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   lat                20285 non-null  float64
 1   lon                20285 non-null  float64
 2   minutes_remaining  20285 non-null  int64
 3   period             20285 non-null  int64
 4   playoffs           20285 non-null  int64
 5   shot_distance      20285 non-null  int64
 6   shot_made_flag     20285 non-null  int32
dtypes: float64(2), int32(1), int64(4)
memory usage: 1.2 MB
None

-------------------------------------------------------------------------------------------------

<class 'pandas.core.frame.DataFrame'>
Index: 5412 entries, 10 to 30695
Data columns (total 7 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   lat                5412 non-null   float64
 1   lon                5412 non-null   float64
 2   minutes_remaining  5412 non-null   int64
 3   period             5412 non-null   int64
 4   playoffs           5412 non-null   int64
 5   shot_distance      5412 non-null   int64
 6   shot_made_flag     5412 non-null   int32
dtypes: float64(2), int32(1), int64(4)
memory usage: 317.1 KB
None

# Analisando dados pós tratamento dos dados brutos

In [9]:
print(df_dataset_kobe_dev.head())
print("________________________________________________________________________________________________")
print(df_dataset_kobe_dev.describe())
print("________________________________________________________________________________________________")
print(df_dataset_kobe_dev.info())
print("________________________________________________________________________________________________")

print()
print("-------------------------------------------------------------------------------------------------")
print()

print(df_dataset_kobe_prod.head())
print("________________________________________________________________________________________________")
print(df_dataset_kobe_prod.describe())
print("________________________________________________________________________________________________")
print(df_dataset_kobe_prod.info())


print(df_dataset_kobe_dev["shot_made_flag"].value_counts())
print("________________________________________________________________________________________________")
print(df_dataset_kobe_prod["shot_made_flag"].value_counts())
print("________________________________________________________________________________________________")

print(df_dataset_kobe_dev["minutes_remaining"].value_counts())
print("________________________________________________________________________________________________")
print(df_dataset_kobe_prod["minutes_remaining"].value_counts())
print("________________________________________________________________________________________________")

print(df_dataset_kobe_dev["shot_distance"].value_counts())
print("________________________________________________________________________________________________")
print(df_dataset_kobe_prod["shot_distance"].value_counts())
print("________________________________________________________________________________________________")

print(df_dataset_kobe_dev["period"].value_counts())
print("________________________________________________________________________________________________")
print(df_dataset_kobe_prod["period"].value_counts())
print("________________________________________________________________________________________________")

print(df_dataset_kobe_dev.isnull().sum())
print("________________________________________________________________________________________________")
print(df_dataset_kobe_prod.isnull().sum())
print("________________________________________________________________________________________________")

       lat       lon  minutes_remaining  period  playoffs  shot_distance  \
1  34.0443 -118.4268                 10       1         0             15
2  33.9093 -118.3708                  7       1         0             16
3  33.8693 -118.1318                  6       1         0             22
4  34.0443 -118.2698                  6       2         0              0
5  34.0553 -118.4148                  9       3         0             14

   shot_made_flag
1               0
2               1
3               0
4               1
5               0
________________________________________________________________________________________________
                lat           lon  minutes_remaining        period  \
count  20285.000000  20285.000000       20285.000000  20285.000000
mean      33.980645   -118.262310           5.100173      2.471974
std        0.065895      0.093401           3.423866      1.148192
min       33.543300   -118.487800           0.000000      1.000000
25%       33.926300   -118.312800           2.000000      1.000000
50%       33.999300   -118.269800           5.000000      3.000000
75%       34.044300   -118.194800           8.000000      3.000000
max       34.088300   -118.049800          11.000000      7.000000

           playoffs  shot_distance  shot_made_flag
count  20285.000000   20285.000000    20285.000000
mean       0.148731      10.216317        0.477348
std        0.355831       7.559547        0.499499
min        0.000000       0.000000        0.000000
25%        0.000000       1.000000        0.000000
50%        0.000000      12.000000        0.000000
75%        0.000000      17.000000        1.000000
max        1.000000      50.000000        1.000000
________________________________________________________________________________________________
<class 'pandas.core.frame.DataFrame'>
Index: 20285 entries, 1 to 30696
Data columns (total 7 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   lat                20285 non-null  float64
 1   lon                20285 non-null  float64
 2   minutes_remaining  20285 non-null  int64
 3   period             20285 non-null  int64
 4   playoffs           20285 non-null  int64
 5   shot_distance      20285 non-null  int64
 6   shot_made_flag     20285 non-null  int32
dtypes: float64(2), int32(1), int64(4)
memory usage: 1.2 MB
None
________________________________________________________________________________________________

-------------------------------------------------------------------------------------------------

        lat       lon  minutes_remaining  period  playoffs  shot_distance  \
10  33.8063 -118.3638                  1       3         0             25
17  33.8183 -118.3868                  8       2         0             25
27  33.8583 -118.4528                  0       3         0             26
39  33.7723 -118.2968                  0       2         0             27
55  33.8503 -118.4248                  2       1         0             24

    shot_made_flag
10               0
17               1
27               0
39               1
55               0
________________________________________________________________________________________________
               lat          lon  minutes_remaining       period     playoffs  \
count  5412.000000  5412.000000        5412.000000  5412.000000  5412.000000
mean     33.849585  -118.263931           4.087029     2.703806     0.136918
std       0.084045     0.157584           3.442213     1.146149     0.343792
min      33.253300  -118.519800           0.000000     1.000000     0.000000
25%      33.805300  -118.422800           1.000000     2.000000     0.000000
50%      33.835300  -118.258800           4.000000     3.000000     0.000000
75%      33.877300  -118.115800           7.000000     4.000000     0.000000
max      34.079300  -118.021800          11.000000     7.000000     1.000000

       shot_distance  shot_made_flag
count    5412.000000     5412.000000
mean       25.604028        0.329268
std         4.174941        0.469991
min         0.000000        0.000000
25%        24.000000        0.000000
50%        25.000000        0.000000
75%        26.000000        1.000000
max        79.000000        1.000000
________________________________________________________________________________________________
<class 'pandas.core.frame.DataFrame'>
Index: 5412 entries, 10 to 30695
Data columns (total 7 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   lat                5412 non-null   float64
 1   lon                5412 non-null   float64
 2   minutes_remaining  5412 non-null   int64
 3   period             5412 non-null   int64
 4   playoffs           5412 non-null   int64
 5   shot_distance      5412 non-null   int64
 6   shot_made_flag     5412 non-null   int32
dtypes: float64(2), int32(1), int64(4)
memory usage: 317.1 KB
None
shot_made_flag
0    10602
1     9683
Name: count, dtype: int64
________________________________________________________________________________________________
shot_made_flag
0    3630
1    1782
Name: count, dtype: int64
________________________________________________________________________________________________
minutes_remaining
0     2088
4     1924
3     1888
2     1884
1     1755
5     1731
6     1585
9     1578
7     1573
10    1517
8     1452
11    1310
Name: count, dtype: int64
________________________________________________________________________________________________
minutes_remaining
0     1160
1      519
2      495
3      489
4      484
5      458
6      396
7      303
9      298
8      297
10     281
11     232
Name: count, dtype: int64
________________________________________________________________________________________________
shot_distance
0     4607
17    1225
18    1195
16    1165
19    1131
20     993
15     972
14     894
13     786
21     671
12     644
7      603
11     602
10     588
8      568
6      557
9      527
1      522
2      483
5      444
22     390
3      319
4      317
23      80
50       1
26       1
Name: count, dtype: int64
________________________________________________________________________________________________
shot_distance
25    1631
24    1263
26    1059
27     450
23     413
22     181
28     166
29      67
31      24
30      16
37      10
40       9
32       8
39       7
38       7
34       7
36       6
42       6
41       5
43       5
58       4
62       4
35       4
33       4
44       4
56       3
55       3
48       3
47       3
74       3
59       2
67       2
46       2
52       2
49       2
63       2
51       2
50       2
64       2
68       2
45       2
60       2
70       2
65       1
53       1
77       1
71       1
69       1
0        1
57       1
61       1
9        1
54       1
79       1
Name: count, dtype: int64
________________________________________________________________________________________________
period
1    5584
3    5563
2    4482
4    4405
5     224
6      22
7       5
Name: count, dtype: int64
________________________________________________________________________________________________
period
4    1638
3    1439
2    1153
1    1116
5      56
6       8
7       2
Name: count, dtype: int64
________________________________________________________________________________________________
lat                  0
lon                  0
minutes_remaining    0
period               0
playoffs             0
shot_distance        0
shot_made_flag       0
dtype: int64
________________________________________________________________________________________________
lat                  0
lon                  0
minutes_remaining    0
period               0
playoffs             0
shot_distance        0
shot_made_flag       0
dtype: int64
________________________________________________________________________________________________

# Analisando dados a tabela de dados produzidos em parquet de resultados obtidos pelo pipeline "PipelineAplicacao"

In [10]:
df_result_kobe_prod = pd.read_parquet("../data/08_reporting/metric_prod_report.parquet", engine="pyarrow")  # ou engine="fastparquet"
df_result_kobe_prod.head()
print("________________________________________________________________________________________________")
print(df_result_kobe_prod.describe())
print("________________________________________________________________________________________________")
print(df_result_kobe_prod.info())

________________________________________________________________________________________________
               lat          lon  minutes_remaining       period     playoffs  \
count  5412.000000  5412.000000        5412.000000  5412.000000  5412.000000
mean     33.849586  -118.263924           4.087029     2.703806     0.136918
std       0.084045     0.157584           3.442213     1.146149     0.343792
min      33.253300  -118.519798           0.000000     1.000000     0.000000
25%      33.805302  -118.422798           1.000000     2.000000     0.000000
50%      33.835300  -118.258797           4.000000     3.000000     0.000000
75%      33.877300  -118.115799           7.000000     4.000000     0.000000
max      34.079300  -118.021797          11.000000     7.000000     1.000000

       shot_distance  shot_made_flag  prediction_label  prediction_score_0  \
count    5412.000000     5412.000000       5412.000000         5412.000000
mean       25.604028        0.329268          0.000185            0.683144
std         4.174941        0.469991          0.013593            0.032289
min         0.000000        0.000000          0.000000            0.400200
25%        24.000000        0.000000          0.000000            0.665900
50%        25.000000        0.000000          0.000000            0.680100
75%        26.000000        1.000000          0.000000            0.694600
max        79.000000        1.000000          1.000000            0.950000

       prediction_score_1
count         5412.000000
mean             0.316856
std              0.032289
min              0.050000
25%              0.305400
50%              0.319900
75%              0.334100
max              0.599800
________________________________________________________________________________________________
<class 'pandas.core.frame.DataFrame'>
Index: 5412 entries, 10 to 30695
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   lat                 5412 non-null   float32
 1   lon                 5412 non-null   float32
 2   minutes_remaining   5412 non-null   int8
 3   period              5412 non-null   int8
 4   playoffs            5412 non-null   int8
 5   shot_distance       5412 non-null   int8
 6   shot_made_flag      5412 non-null   int8
 7   prediction_label    5412 non-null   int32
 8   prediction_score_0  5412 non-null   float64
 9   prediction_score_1  5412 non-null   float64
dtypes: float32(2), float64(2), int32(1), int8(5)
memory usage: 216.7 KB
None

# Analise dos dados de 02_intermediate

In [12]:
df_dataset_kobe_prod = pd.read_parquet("../data/02_intermediate/dataset_kobe_prod.parquet", engine="pyarrow") 
print(df_dataset_kobe_prod.info())
print("________________________________________________________________________________________________")
print()
df_dataset_kobe_dev = pd.read_parquet("../data/02_intermediate/dataset_kobe_dev.parquet", engine="pyarrow") 
print(df_dataset_kobe_dev.info())
print("________________________________________________________________________________________________")

<class 'pandas.core.frame.DataFrame'>
Index: 5412 entries, 10 to 30695
Data columns (total 7 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   lat                5412 non-null   float64
 1   lon                5412 non-null   float64
 2   minutes_remaining  5412 non-null   int64
 3   period             5412 non-null   int64
 4   playoffs           5412 non-null   int64
 5   shot_distance      5412 non-null   int64
 6   shot_made_flag     5412 non-null   int32
dtypes: float64(2), int32(1), int64(4)
memory usage: 317.1 KB
None
________________________________________________________________________________________________

<class 'pandas.core.frame.DataFrame'>
Index: 20285 entries, 1 to 30696
Data columns (total 7 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   lat                20285 non-null  float64
 1   lon                20285 non-null  float64
 2   minutes_remaining  20285 non-null  int64
 3   period             20285 non-null  int64
 4   playoffs           20285 non-null  int64
 5   shot_distance      20285 non-null  int64
 6   shot_made_flag     20285 non-null  int32
dtypes: float64(2), int32(1), int64(4)
memory usage: 1.2 MB
None
________________________________________________________________________________________________

# Analise dos dados de 05_model_input

In [13]:

df_dataset_kobe_train_dev = pd.read_parquet("../data/05_model_input/dataset_kobe_dev.parquet", engine="pyarrow") 
print(df_dataset_kobe_train_dev.info())
print("________________________________________________________________________________________________")
print()
df_dataset_kobe_test_dev = pd.read_parquet("../data/05_model_input/dataset_kobe_test_dev.parquet", engine="pyarrow") 
print(df_dataset_kobe_test_dev.info())
print("________________________________________________________________________________________________")

<class 'pandas.core.frame.DataFrame'>
Index: 16228 entries, 3066 to 18911
Data columns (total 7 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   lat                16228 non-null  float32
 1   lon                16228 non-null  float32
 2   minutes_remaining  16228 non-null  int8
 3   period             16228 non-null  int8
 4   playoffs           16228 non-null  int8
 5   shot_distance      16228 non-null  int8
 6   shot_made_flag     16228 non-null  int8
dtypes: float32(2), int8(5)
memory usage: 332.8 KB
None
________________________________________________________________________________________________

<class 'pandas.core.frame.DataFrame'>
Index: 4057 entries, 11048 to 25721
Data columns (total 7 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   lat                4057 non-null   float32
 1   lon                4057 non-null   float32
 2   minutes_remaining  4057 non-null   int8
 3   period             4057 non-null   int8
 4   playoffs           4057 non-null   int8
 5   shot_distance      4057 non-null   int8
 6   shot_made_flag     4057 non-null   int8
dtypes: float32(2), int8(5)
memory usage: 83.2 KB
None
________________________________________________________________________________________________